#version: '{build}'
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - ps: $env:BUILD_NUMBER=$env:APPVEYOR_BUILD_NUMBER
  - ps: ./build.cmd
test: off
artifacts:
  - path: './artifacts/*.nupkg'
    name: NuGet
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/lethargicdeveloper/api/v2/package
    api_key:
      secure: Jjf/28XFNSoemMibRmtyttdDFf1s9TGpAGra0CWyLFgFW69rEe5qBeEahdq9Cl8v
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    name: production
    api_key:
      secure: rYW/9ptc6daqi3EnbDyNGHJ0iJfBqT/hp2m/0P5rySNX7xDA9xrDi5dQanSAAMVe
    on:
      branch: master
      appveyor_repo_tag: true