image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
test: off
assembly_info:
  patch: false
artifacts:
  - path: '.\artifacts\*.nupkg'
    name: NuGet

for:
# master - release
-
  branches:
    only:
      - master
  build_script:
  - ps: .\build.cmd -configuration Release -pack
  deploy:
    - provider: NuGet
      name: production
      api_key:
        secure: 0xScMBscH8iJ/a80e1dFkMc/ehAYd1FoeiZ/QmTe14TOlR/xt0H3lfxhphxnJfko
      on:
        branch: master
        appveyor_repo_tag: true

# master - develop
-
  branches:
    only:
      - master
  build_script:
  - ps: .\build.cmd -configuration Debug -pack
  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/lethargicdeveloper/api/v2/package
      skip_symbols: false
      symbol_server: https://www.myget.org/F/lethargicdeveloper/symbols/api/v2/package
      api_key:
        secure: Jjf/28XFNSoemMibRmtyttdDFf1s9TGpAGra0CWyLFgFW69rEe5qBeEahdq9Cl8v
      on:
        branch: master
        appveyor_repo_tag: true