image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
test: off
build_script:
  - ps: .\build.cmd
configuration: Debug
artifacts:
  - path: '.\artifacts\*.nupkg'
    name: NuGet

for:
# master
-
  branches:
    only:
      - master
  configuration: Release
  deploy:
    - provider: NuGet
      name: production
      api_key:
        secure: 0xScMBscH8iJ/a80e1dFkMc/ehAYd1FoeiZ/QmTe14TOlR/xt0H3lfxhphxnJfko
      on:
        branch: master
        appveyor_repo_tag: true

# develop
-
  branches:
    only:
      - develop
  configuration: Debug
  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/lethargicdeveloper/api/v2/package
      api_key:
        secure: Jjf/28XFNSoemMibRmtyttdDFf1s9TGpAGra0CWyLFgFW69rEe5qBeEahdq9Cl8v
      on:
        branch: develop